# Generated by Django 3.2 on 2024-02-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Пользователь'},
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_moderator',
        ),
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография пользователя'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Administrator')], default='user', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddConstraint(
            model_name='myuser',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, username__iexact='me'), name='Username me is not valid'),
        ),
    ]
